/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-05 08:21:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class home1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
request.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>后台管理系统</title>\r\n");
      out.write("    <meta content=\"IE=11.0000\" http-equiv=\"X-UA-Compatible\">\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("hybrid/css/reset.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("hybrid/css/public.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("hybrid/css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("hybrid/css/css.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("hybrid/js/sdmenu.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t<!-- 顶部 --> \r\n");
      out.write("    <header>\r\n");
      out.write("\t  <h1><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("images/home/admin_logo.png\"/></h1>\r\n");
      out.write("\t    <ul class=\"rt_nav\">\r\n");
      out.write("\t    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("login/login.jsp\" target=\"_blank\" class=\"website_icon\">站点首页</a></li>\r\n");
      out.write("\t    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("login/login.jsp\" class=\"set_icon\">账号设置</a></li>\r\n");
      out.write("\t    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("login/login.jsp\" class=\"quit_icon\">安全退出</a></li>\r\n");
      out.write("\t  </ul>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!-- 顶部 --> \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 内容展示 -->\r\n");
      out.write("\t<div class=\"public-ifame mt20\">\r\n");
      out.write("\t  <div class=\"content\">\r\n");
      out.write("\t    <!-- 内容模块头 -->\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t<!-- 左侧导航栏 -->\r\n");
      out.write("\t\t<div class=\"public-ifame-leftnav\">\r\n");
      out.write("\t\t\t<ul class=\"left-nav-list\">\r\n");
      out.write("\t\t\t\t<li class=\"public-ifame-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\">系统管理</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"ifame-item-sub\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"/login/login.jsp\" target=\"content\">用户管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/login/login.jsp\" target=\"content\">角色管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/login/login.jsp\" target=\"content\">权限管理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/login/login.jsp\" target=\"content\">菜单配置</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"public-ifame-item\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\">入驻商</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 右侧内容展示部分 -->\r\n");
      out.write("\t\t<div class=\"public-ifame-content\">\r\n");
      out.write("\t\t<iframe name=\"content\" src=\"/login/login.jsp\" frameborder=\"0\" id=\"mainframe\" scrolling=\"yes\" marginheight=\"0\" marginwidth=\"0\" width=\"100%\" style=\"height: 700px;\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$().ready(function(){\r\n");
      out.write("\tvar item = $(\".public-ifame-item\");\r\n");
      out.write("\r\n");
      out.write("\tfor(var i=0; i < item.length; i++){\r\n");
      out.write("\t\t$(item[i]).on('click',function(){\r\n");
      out.write("\t\t\t$(\".ifame-item-sub\").hide();\r\n");
      out.write("\t\t\tif($(this.lastElementChild).css('display') == 'block'){\r\n");
      out.write("\t\t\t\t$(this.lastElementChild).hide()\r\n");
      out.write("\t\t\t\t$(\".ifame-item-sub li\").removeClass(\"active\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(this.lastElementChild).show();\r\n");
      out.write("\t\t\t\t$(\".ifame-item-sub li\").on('click',function(){\r\n");
      out.write("\t\t\t\t\t$(\".ifame-item-sub li\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
