/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-03 08:45:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
response.setHeader("X-UA-Compatible","IE=edge");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>IYW</title>\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"iyw\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"iyw\">\r\n");
      out.write("\t<!-- bootstrap-css -->\r\n");
      out.write("\t<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\t<!--// bootstrap-css -->\r\n");
      out.write("\t<!-- css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\t<!--// css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/ken-burns.css\">\r\n");
      out.write("\t<!-- font-awesome icons -->\r\n");
      out.write("\t<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("\t<!-- //font-awesome icons -->\r\n");
      out.write("\t<!-- font -->\r\n");
      out.write("\t<link href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("fonts/css/font_1.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("fonts/css/font_2.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<!-- //font -->\r\n");
      out.write("\t<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t<!-- banner -->\r\n");
      out.write("\t<div class=\"banner\">\r\n");
      out.write("\t  <div class=\"top-banner\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"top-banner-left\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i> +86 182 6801 1224</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mailto:example@email.com\"><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> 2654827818@qq.com</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"top-banner-right\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"facebook\" href=\"#\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\">IYW</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"top-nav\">\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">Menu\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"index.jsp\">首页</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"about.html\">商品中心</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"services.html\">新闻资讯</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"services.html\">客户留言</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"services.html\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</nav>\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //banner -->\r\n");
      out.write("\t\t<div id=\"kb\" class=\"carousel kb_elastic animate_text kb_wrapper\" data-ride=\"carousel\" data-interval=\"6000\" data-pause=\"hover\">\r\n");
      out.write("\t            <!-- Wrapper for Slides -->\r\n");
      out.write("\t            <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t                <!-- First Slide -->\r\n");
      out.write("\t                <div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption kb_caption slider-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>林心如</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>美女.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- Second Slide -->\r\n");
      out.write("\t                <div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider slider1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption kb_caption kb_caption_right slider-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>泰勒斯威夫特</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>乡村音乐歌手.</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- Third Slide -->\r\n");
      out.write("\t                <div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider slider2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption kb_caption kb_caption_center slider-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t   <h3>林志玲</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>台湾第一美女</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- Navigation Buttons -->\r\n");
      out.write("\t            <!-- Left Button -->\r\n");
      out.write("\t            <a class=\"left carousel-control kb_control_left\" href=\"#kb\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t                <span class=\"fa fa-angle-left kb_icons\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <!-- Right Button -->\r\n");
      out.write("\t            <a class=\"right carousel-control kb_control_right\" href=\"#kb\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t                <span class=\"fa fa-angle-right kb_icons\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t                <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t    </div> \r\n");
      out.write("\t\t<!-- about -->\r\n");
      out.write("\t\t<div class=\"about\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"w3l-about-heading\">\r\n");
      out.write("\t\t\t\t\t<h2>新品上架</h2>\r\n");
      out.write("\t\t\t\t\t<p>只为您更满意.</P>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"about-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 about-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-grid-info effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>衣服1</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 about-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-grid-info about-grid-info1 effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>衣服2</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 about-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-grid-info about-grid-info2 effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>衣服3</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 about-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"about-grid-info about-grid-info3 effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>衣服4</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //about -->\r\n");
      out.write("\t\t<!-- offer -->\r\n");
      out.write("\t\t<div class=\"offer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"wthree-offer-grid\">\r\n");
      out.write("\t\t\t\t\t<h4>TOP 10</h4>\r\n");
      out.write("\t\t\t\t\t<p>Sed vitae purus ut libero malesuada molestie imperdiet a nibh. Etiam consectetur odio a massa vulputate porttitor. Quisque nibh orci, vestibulum sed gravida vel, eleifend nec libero. </p>\r\n");
      out.write("\t\t\t\t\t<div class=\"click-button\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"single.html\">Click Here</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //offer -->\r\n");
      out.write("\t\t<!-- news -->\r\n");
      out.write("\t\t<div class=\"news\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"news-heading\">\r\n");
      out.write("\t\t\t\t\t<h3>销售热榜</h3>\r\n");
      out.write("\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta efficitur ante quis volutpat.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"news-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 news-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile-news-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/girl/1.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"admin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i> 甜甜</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i> June 1,2016</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quisque gravida, nunc eu interdum porta</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Aliquam erat volutpat. Duis vulputate tempus laoreet. Integer viverra eleifend neque, eget dictum lectus. Quisque eu tempor dolor.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 news-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile-news-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/girl/2.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"admin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i> 馨儿</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i> May 09,2016</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quisque gravida, nunc eu interdum porta</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Aliquam erat volutpat. Duis vulputate tempus laoreet. Integer viverra eleifend neque, eget dictum lectus. Quisque eu tempor dolor.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 news-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"agile-news-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"single.html\"><img src=\"images/girl/3.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"date-grid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"admin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-user\" aria-hidden=\"true\"></i> 香香</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"time\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p><i class=\"fa fa-calendar\" aria-hidden=\"true\"></i> May 09,2016</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"news-grid-info-bottom-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"single.html\">Quisque gravida, nunc eu interdum porta</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Aliquam erat volutpat. Duis vulputate tempus laoreet. Integer viverra eleifend neque, eget dictum lectus. Quisque eu tempor dolor.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //news -->\r\n");
      out.write("\t\t<!-- footer -->\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-grids\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>地址</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>中国 浙江省 杭州市\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>西湖区古翠路320号.</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"phone\">Phone : +86 182 6801 1224\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>Email : <a href=\"2654827818@qq.com\">2654827818@qq.com</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>导航</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"about.html\">商品中心</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"services.html\">新闻资讯</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"gallery.html\">客户留言</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Follow</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-rss\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-vk\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 footer-grid\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>访客留言</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-grid-info\">\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"email\" id=\"mc4wp_email\" name=\"EMAIL\" placeholder=\"Enter your email here\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"提交\">\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t<p>Copyright &copy; 2016.Company name All rights reserved.<a target=\"_blank\" href=\"http://172.16.66.38:19232/index.jsp\">DJM</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- //footer -->\r\n");
      out.write("\t\t<script src=\"js/SmoothScroll.min.js\"></script>\r\n");
      out.write("\t</body>\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
