/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-05 08:56:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
request.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>布局</title>\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t  html{\r\n");
      out.write("\t    overflow-y:hidden;\r\n");
      out.write("\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t  body{\r\n");
      out.write("\t    margin:0;\r\n");
      out.write("\t    height:100%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .container{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .header{\r\n");
      out.write("\t\tbackground:#19a97b; \r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:12%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t   .mainPage{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:88%;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .sidebar{\r\n");
      out.write("\t\tbackground:#FFFFFF;\r\n");
      out.write("\t\twidth:16%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\toverflow:auto;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .content{\r\n");
      out.write("\t\tbackground:#DBEAF9;\r\n");
      out.write("\t\twidth:84%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\toverflow:auto;\r\n");
      out.write("\t  }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- 页面层容器 -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <!-- 页面头部 -->\r\n");
      out.write("      <div class=\"header\">页面头部</div>\r\n");
      out.write("      <!-- 页面主体 -->\r\n");
      out.write("      <div class=\"mainPage\">\r\n");
      out.write("        <!-- 侧边栏 -->\r\n");
      out.write("        <div class=\"sidebar\">侧边栏</div>\r\n");
      out.write("        <!-- 主体内容 -->\r\n");
      out.write("        <div class=\"content\">内容</div>\r\n");
      out.write("      </div>\t\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
