/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-08 06:16:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
request.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>管理首页 | IYW用户中心</title>\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta content=\"IE=11.0000\" http-equiv=\"X-UA-Compatible\">\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/css/framework.css\" />\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"page\">\r\n");
      out.write("<!--header begin-->\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"bigcontainer\">\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"./\">yeelink用户中心</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t<div class=\"ui compact notif menu\">\r\n");
      out.write("\t\t\t  <a class=\"item\">\r\n");
      out.write("\t\t\t\t<i class=\"mail large icon\"></i>\r\n");
      out.write("\t\t\t\t<span class=\"circular floating ui small red label\"> 2 </span>\r\n");
      out.write("\t\t\t  </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <div class=\"ui inline labeled icon top right pointing dropdown\">\r\n");
      out.write("                <img class=\"ui avatar image\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/images/avatar-default.gif\">\r\n");
      out.write("\t\t\t欢迎，$用户名\r\n");
      out.write("\t\t\t<i class=\"dropdown icon\"></i>\r\n");
      out.write("\t\t\t\t<div class=\"menu\">\r\n");
      out.write("\t\t\t\t\t<a class=\"item\" href=\"http://www.yeelink.net\"><i class=\"reply mail icon\"></i>返回首页</a>\r\n");
      out.write("\t\t\t\t\t<a class=\"item\" href=\"/login/login.jsp\"><i class=\"sign out icon\"></i>注销登录</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- the main menu-->\r\n");
      out.write("<div class=\"ui teal inverted menu\">\r\n");
      out.write("\t<div class=\"bigcontainer\">\r\n");
      out.write("\t\t<div class=\"right menu\">\r\n");
      out.write("\t\t\t<a class=\"active item\" href=\"./index.html\"><i class=\"home icon\"></i>管理首页</a>\r\n");
      out.write("\t\t\t<a class=\"item\" href=\"./devices_list.html\"><i class=\"sitemap icon\"></i>设备</a>\r\n");
      out.write("            <a class=\"item\" href=\"./product_list.html\"><i class=\"cloud icon\"></i>产品</a>\r\n");
      out.write("\t\t\t<a class=\"item\" href=\"./user_profile.html\"><i class=\"info icon\"></i>账户</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--the main content begin-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t<!--the content-->\r\n");
      out.write("\t\t<div class=\"pageHeader\">\r\n");
      out.write("\t\t\t<div class=\"segment\">\r\n");
      out.write("\t\t\t\t<h3 class=\"ui dividing header\">\r\n");
      out.write("  \t\t\t\t\t<i class=\"large home icon\"></i>\r\n");
      out.write("  \t\t\t\t\t<div class=\"content\">\r\n");
      out.write("    \t\t\t\t\t管理首页\r\n");
      out.write("    \t\t\t\t<div class=\"sub header\">快速查看和编辑</div>\r\n");
      out.write("  \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <div class=\"ui warning message\">\r\n");
      out.write("            \t<i class=\"close icon\" data-dismiss=\"alert\"></i>\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("            \t<i class=\"warning icon\"></i> 当前帐户还未激活.\r\n");
      out.write("            </div>\r\n");
      out.write("            未激活账户无法使用Yeelink服务，请检查注册时填写的邮箱，完成验证。\r\n");
      out.write("            <a href=\"http://www.yeelink.net/login/resend_activate_mail\" title=\"重新发送激活邮件\">未收到激活邮件？</a>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"ui small message\" id=\"showApiKey\">\r\n");
      out.write("           <div class=\"ui form segment\">\r\n");
      out.write("                <div class=\"inline field\">\r\n");
      out.write("                    <label>您的API Key :</label>\r\n");
      out.write("                    <div class=\"ui small left icon input short\">\r\n");
      out.write("                        <i class=\"key icon\"></i>\r\n");
      out.write("                        <input type=\"text\" value=\"793jIEGJjkjkljfUI3JRTJOIO\" readonly=\"readonly\" id=\"apiKey\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a class=\"ui mini green button\" id=\"copy-apiKey\" href=\"#\">复制</a>\r\n");
      out.write("                    <a class=\"ui mini blue animated button\" href=./apikey_manage.html>\r\n");
      out.write("                        <span class=\"visible content\">管理</span>\r\n");
      out.write("                        <span class=\"hidden content\">\r\n");
      out.write("                            <i class=\"key icon\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a id=\"deviceQuickButton\" class=\"ui red small labeled icon button\" href=\"./devices_list.html\">\r\n");
      out.write("                        <i class=\"settings icon\"></i>管理所有设备\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\t<!--device list-->\r\n");
      out.write("\t<div class=\"ui three column grid\" id=\"indexList\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"ui blue segment\">\r\n");
      out.write("\t\t\t\t\t<a href=\"./device.html\" class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"deviceName\">设备名01</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceId\">设备ID：234</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceDescription\">这里是设备描述。</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sensorStatus\">传感器状态：\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui red error label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                        </p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"ui blue segment\">\r\n");
      out.write("\t\t\t\t\t<a class=\"content\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"deviceName\">设备名02</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceId\">设备ID：4354</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceDescription\">这里是设备描述。</p>\r\n");
      out.write("                        <p class=\"sensorStatus\">传感器状态：\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                        </p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"ui blue segment\">\r\n");
      out.write("\t\t\t\t\t<a class=\"content\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"deviceName\">设备名03</h4>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceId\">设备ID：344</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"deviceDescription\">这里是设备描述。</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"sensorStatus\">传感器状态：\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                            <span class=\"ui green ok label\" ></span>\r\n");
      out.write("                        </p>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<div class=\"ui blue segment\">\r\n");
      out.write("\t\t\t\t\t<a class=\"content\" href=\"./add.html\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"newDevice\"><i class=\"huge add icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t添加新设备</h4>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--footer begin-->\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div id=\"copyrights\">\r\n");
      out.write("\t\t<div class=\"inset\">\r\n");
      out.write("\t\t\t<div class=\"bigcontainer\">\r\n");
      out.write("\t\t\t\t<div class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\"></div>\r\n");
      out.write("\t\t\t\t\t<p>&copy; 2020 浙江三只眼信息技术有限公司, 版权所有 <a href=\"http://www.baidu.com/\" target=\"_blank\">iyw</a><br />\r\n");
      out.write("<a href=\"http://www.miibeian.gov.cn\" target=\"_blank\">浙ICP备12022271号</a></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/javascript/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/javascript/framework.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/javascript/jquery.zclip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("temp/resource/javascript/alert.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$('a#copy-apiKey').zclip({\r\n");
      out.write("\t\t\tpath:'/temp/resource/javascript/ZeroClipboard.swf',\r\n");
      out.write("\t\t\tcopy:function(){return $('input#apiKey').val();}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.ui.dropdown')\r\n");
      out.write("\t\t\t.dropdown();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
