/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-10-15 09:11:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.security;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class MyJsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
request.setAttribute("basePath", basePath);

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("  <title>登录页面</title>\r\n");
      out.write("  <meta content=\"IE=11.0000\" http-equiv=\"X-UA-Compatible\">\r\n");
      out.write("  <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("  <meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("  <meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("  <meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("  <meta http-equiv=\"keywords\" content=\"DJM,IYW\">\r\n");
      out.write("  <meta http-equiv=\"description\" content=\"LOGIN\">\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("bootstrap/css/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("css/login/login.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("js/login/login.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"top_div\"></div>\r\n");
      out.write("  <div class=\"big_div\">\r\n");
      out.write("    <div class=\"anime_div\">\r\n");
      out.write("      <div class=\"tou\"></div>\r\n");
      out.write("      <div class=\"initial_left_hand\" id=\"left_hand\"></div>\r\n");
      out.write("      <div class=\"initial_right_hand\" id=\"right_hand\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form class=\"form-inline\" role=\"form\" action=\"/login\" method='POST'>\r\n");
      out.write("   \t  <input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>   \r\n");
      out.write("  \t  <div class=\"form-group\" style=\"padding: 30px 0px 10px; position: relative;\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <div class=\"input-group-addon\">用户名:</div>\r\n");
      out.write("          <input name=\"username\" class=\"form-control\" type=\"text\" style=\"width:230px;\" placeholder=\"请输入用户名或邮箱\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\" style=\"position: relative;\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <div class=\"input-group-addon\">&nbsp;&nbsp;&nbsp;密码:</div>\r\n");
      out.write("          <input name=\"password\" id=\"password\" class=\"form-control\" type=\"password\" style=\"width:230px;\" placeholder=\"请输入密码\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"bottom_div\">\r\n");
      out.write("\t    <p style=\"margin: 0px 35px 20px 45px;\">\r\n");
      out.write("\t      <span class=\"forget_span\"><a class=\"forget_a\" href=\"#\">忘记密码?</a></span> \r\n");
      out.write("          <span class=\"register_span\">\r\n");
      out.write("          \t<a class=\"register_a\" href=\"#\">注册</a>\r\n");
      out.write("          \t<button type=\"submit\" class=\"btn btn-warning\">登录</button>\r\n");
      out.write("          </span>         \r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
